### ISSUE TITLE
Only the first one prints the result in the console if call printInvert() and print() 

### ISSUE THREAD

**Issue by LukyGuyLucky** [fillipehmeireles/c3-double-linked-list#1]
Thank you for this great example!

With the most recent updated c3c (binary release today),I tried to compile and run it under windows10,64bit.It runs as the code expected.

But when I try to add ll.print();after ll.printInvert();print() prints nothing.If I change the oder of the two functions,only the first one prints the result,the second one just print blank.

Was I missing something?

Thank you for the help in advance.

**Comment by fillipehmeireles** [comment]
Hey @LukyGuyLucky , appreciate your comment.
This happens because the print and printInvert functions are receiving the list pointer. As these functions run through the list nodes, the node that the next function receives is null, thats why its not displaying anything.
I just changed the functions to receive a copy instead of its pointer. Please take a look ;) 

Print Function
https://github.com/fillipehmeireles/c3-double-linked-list/blob/2d5216fb13effee9333196ec1f8effe5b696a4a2/doublelinkedlist.c3#L62

Print Invert Function
https://github.com/fillipehmeireles/c3-double-linked-list/blob/2d5216fb13effee9333196ec1f8effe5b696a4a2/doublelinkedlist.c3#L46

**Comment by LukyGuyLucky** [comment]
Thank you very much for the help! Now the second call prints correctly.
